/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Restaurant_s;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Random;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.UnsupportedLookAndFeelException;
/**
 *
 * @author User
 */
public class Restaurants extends javax.swing.JFrame {
    
    /**
     *
     */
 
    
   double firstnum;
   double secondnum;
   double result;
   String operations;
   
   double [] i = new double[5];
   double US_Dollar = 0.0121;
   double Cnadian_Dollar = 0.0152;
   double Indian_Rupee = 0.778;
   double Japanese_Yen = 1.13;
   double  Chinese_Yuan_Renminbi = 0.0763;
   double SriLanka_Rupee = 1.86;
   
    /**
     * Creates new form Restaurants
     */
    public Restaurants() {
        initComponents();
     //jPanel10.setBackground(new Color(0,0,0,60));
     // jtxChickBurger.setBackground(new Color(0,0,0,20));
     // jPanel4.setBackground(new Color(0,0,0,60));
     // jPanel1.setBackground(new Color(0,0,0,60));
      //jTabbedPane2.setBackground(new Color(0,0,0,60));
     // jPanel5.setBackground(new Color(0,0,0,60));
     // jPanel3.setBackground(new Color(0,0,0,60));
    //  jPanel6.setBackground(new Color(0,0,0,60));
     // jPanel6.setBackground(new Color(0,0,0,60));
     // jPanel2.setBackground(new Color(0,0,0,60));
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel8 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jCChickBurger = new javax.swing.JCheckBox();
        jCChickBurgerMeal = new javax.swing.JCheckBox();
        jCBacCheeBurger = new javax.swing.JCheckBox();
        jtxChickBurger = new javax.swing.JTextField();
        jtxChickBurgerMeal = new javax.swing.JTextField();
        jtxBacCheeBurger = new javax.swing.JTextField();
        jCTax = new javax.swing.JCheckBox();
        jCDelivery = new javax.swing.JCheckBox();
        jcmbDrink = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jlblCostodDrinks = new javax.swing.JTextField();
        jlblCostofMeal = new javax.swing.JTextField();
        jlblCostofDelivary = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jBtnTotal = new javax.swing.JButton();
        jBtnReceipt = new javax.swing.JButton();
        jBtnReset = new javax.swing.JButton();
        jBtnExit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jcmbCurrency = new javax.swing.JComboBox<>();
        jBtnConvert = new javax.swing.JButton();
        jBtnClose = new javax.swing.JButton();
        jtxConvertor = new javax.swing.JTextField();
        jlblConvertor = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jlblSubTotal = new javax.swing.JTextField();
        jlblTax = new javax.swing.JTextField();
        jlblAllTotal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel9 = new javax.swing.JPanel();
        jtxtDisplay = new javax.swing.JTextField();
        jBtn13 = new javax.swing.JButton();
        jBtn7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jBtn14 = new javax.swing.JButton();
        Jbtn8 = new javax.swing.JButton();
        jBtn4 = new javax.swing.JButton();
        jBtn5 = new javax.swing.JButton();
        jBtn1 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jBtn15 = new javax.swing.JButton();
        jBtn9 = new javax.swing.JButton();
        jBtn6 = new javax.swing.JButton();
        jBtn3 = new javax.swing.JButton();
        jBtn2 = new javax.swing.JButton();
        jBtn16 = new javax.swing.JButton();
        jBtn17 = new javax.swing.JButton();
        jBtn18 = new javax.swing.JButton();
        jBtn19 = new javax.swing.JButton();
        jBtn10 = new javax.swing.JButton();
        jBtn12 = new javax.swing.JButton();
        jBtn11 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jTextField1.setText("Restaurent Managemrnt System");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 0));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1310, 800));
        getContentPane().setLayout(null);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1653, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1308, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel8);
        jPanel8.setBounds(7803, 494, 1653, 1308);

        jPanel10.setBackground(new java.awt.Color(51, 51, 51));
        jPanel10.setToolTipText("");
        jPanel10.setPreferredSize(new java.awt.Dimension(1310, 800));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 51));
        jLabel1.setText("Restaurant Management System");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jCChickBurger.setBackground(new java.awt.Color(204, 204, 204));
        jCChickBurger.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCChickBurger.setForeground(new java.awt.Color(255, 255, 255));
        jCChickBurger.setText("Chicken Burger");
        jCChickBurger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCChickBurgerMouseClicked(evt);
            }
        });
        jCChickBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCChickBurgerActionPerformed(evt);
            }
        });

        jCChickBurgerMeal.setBackground(new java.awt.Color(204, 204, 204));
        jCChickBurgerMeal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCChickBurgerMeal.setForeground(new java.awt.Color(255, 255, 255));
        jCChickBurgerMeal.setLabel("Chicken Burger Meal");
        jCChickBurgerMeal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCChickBurgerMealMouseClicked(evt);
            }
        });
        jCChickBurgerMeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCChickBurgerMealActionPerformed(evt);
            }
        });

        jCBacCheeBurger.setBackground(new java.awt.Color(204, 204, 204));
        jCBacCheeBurger.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCBacCheeBurger.setForeground(new java.awt.Color(255, 255, 255));
        jCBacCheeBurger.setText(" Beacon and Chees Burger");
        jCBacCheeBurger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCBacCheeBurgerMouseClicked(evt);
            }
        });
        jCBacCheeBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBacCheeBurgerActionPerformed(evt);
            }
        });

        jtxChickBurger.setBackground(new java.awt.Color(51, 51, 51));
        jtxChickBurger.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtxChickBurger.setForeground(new java.awt.Color(255, 255, 255));
        jtxChickBurger.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255)));
        jtxChickBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxChickBurgerActionPerformed(evt);
            }
        });

        jtxChickBurgerMeal.setBackground(new java.awt.Color(51, 51, 51));
        jtxChickBurgerMeal.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jtxChickBurgerMeal.setForeground(new java.awt.Color(255, 255, 255));
        jtxChickBurgerMeal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 255)));

        jtxBacCheeBurger.setBackground(new java.awt.Color(51, 51, 51));
        jtxBacCheeBurger.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jtxBacCheeBurger.setForeground(new java.awt.Color(255, 255, 255));
        jtxBacCheeBurger.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));

        jCTax.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCTax.setForeground(new java.awt.Color(255, 255, 255));
        jCTax.setText("Tax");
        jCTax.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCTaxMouseClicked(evt);
            }
        });
        jCTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTaxActionPerformed(evt);
            }
        });

        jCDelivery.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCDelivery.setForeground(new java.awt.Color(255, 255, 255));
        jCDelivery.setText("Home Delivery");
        jCDelivery.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCDeliveryMouseClicked(evt);
            }
        });
        jCDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCDeliveryActionPerformed(evt);
            }
        });

        jcmbDrink.setBackground(new java.awt.Color(0, 255, 102));
        jcmbDrink.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcmbDrink.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a Drink", "Coffe", "Cold Coffe", "Ice Tea", "Apple juece", "Lassi", "" }));
        jcmbDrink.setBorder(null);
        jcmbDrink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbDrinkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jCTax)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCDelivery))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCChickBurgerMeal)
                            .addComponent(jCBacCheeBurger)
                            .addComponent(jCChickBurger))
                        .addGap(74, 74, 74)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxChickBurger)
                            .addComponent(jtxChickBurgerMeal)
                            .addComponent(jtxBacCheeBurger)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jcmbDrink, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCChickBurger)
                    .addComponent(jtxChickBurger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxChickBurgerMeal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCChickBurgerMeal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxBacCheeBurger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBacCheeBurger))
                .addGap(18, 18, 18)
                .addComponent(jcmbDrink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCTax)
                    .addComponent(jCDelivery))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jlblCostodDrinks.setBackground(new java.awt.Color(51, 51, 51));
        jlblCostodDrinks.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblCostodDrinks.setForeground(new java.awt.Color(255, 255, 255));
        jlblCostodDrinks.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jlblCostodDrinks.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255)));
        jlblCostodDrinks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlblCostodDrinksActionPerformed(evt);
            }
        });

        jlblCostofMeal.setBackground(new java.awt.Color(51, 51, 51));
        jlblCostofMeal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblCostofMeal.setForeground(new java.awt.Color(255, 255, 255));
        jlblCostofMeal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jlblCostofMeal.setText("0");
        jlblCostofMeal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 1, true));

        jlblCostofDelivary.setBackground(new java.awt.Color(51, 51, 51));
        jlblCostofDelivary.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblCostofDelivary.setForeground(new java.awt.Color(255, 255, 255));
        jlblCostofDelivary.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jlblCostofDelivary.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255)));
        jlblCostofDelivary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlblCostofDelivaryActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cost of Drinks:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cost of Meal:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cost Delivary:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jlblCostodDrinks)
                    .addComponent(jlblCostofMeal, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(jlblCostofDelivary))
                .addGap(24, 24, 24))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlblCostodDrinks)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlblCostofMeal)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblCostofDelivary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jBtnTotal.setBackground(new java.awt.Color(51, 51, 255));
        jBtnTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtnTotal.setText("Total");
        jBtnTotal.setBorder(null);
        jBtnTotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnTotalMouseClicked(evt);
            }
        });
        jBtnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTotalActionPerformed(evt);
            }
        });

        jBtnReceipt.setBackground(new java.awt.Color(255, 102, 51));
        jBtnReceipt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtnReceipt.setText("Receipt");
        jBtnReceipt.setBorder(null);
        jBtnReceipt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnReceiptMouseClicked(evt);
            }
        });
        jBtnReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnReceiptActionPerformed(evt);
            }
        });

        jBtnReset.setBackground(new java.awt.Color(0, 153, 204));
        jBtnReset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtnReset.setText("Reset");
        jBtnReset.setBorder(null);
        jBtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnResetActionPerformed(evt);
            }
        });

        jBtnExit.setBackground(new java.awt.Color(204, 0, 0));
        jBtnExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtnExit.setText("Exit");
        jBtnExit.setBorder(null);
        jBtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExitActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setText("Add Employee");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jBtnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jBtnReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jBtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jcmbCurrency.setBackground(new java.awt.Color(204, 0, 51));
        jcmbCurrency.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcmbCurrency.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chose one", "USA", "Canada", "India", "Japan", "Sri Lanka", "China", " " }));
        jcmbCurrency.setBorder(null);

        jBtnConvert.setBackground(new java.awt.Color(0, 153, 153));
        jBtnConvert.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtnConvert.setText("Convert");
        jBtnConvert.setBorder(null);
        jBtnConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConvertActionPerformed(evt);
            }
        });

        jBtnClose.setBackground(new java.awt.Color(204, 0, 51));
        jBtnClose.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtnClose.setText("Close");
        jBtnClose.setBorder(null);
        jBtnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCloseActionPerformed(evt);
            }
        });

        jtxConvertor.setBackground(new java.awt.Color(51, 51, 51));
        jtxConvertor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxConvertor.setForeground(new java.awt.Color(255, 255, 255));
        jtxConvertor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxConvertor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));

        jlblConvertor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblConvertor.setForeground(new java.awt.Color(255, 255, 255));
        jlblConvertor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblConvertor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jBtnConvert, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jcmbCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlblConvertor, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxConvertor, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jcmbCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtxConvertor, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlblConvertor, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnClose, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jBtnConvert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jlblSubTotal.setBackground(new java.awt.Color(51, 51, 51));
        jlblSubTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblSubTotal.setForeground(new java.awt.Color(255, 255, 255));
        jlblSubTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jlblSubTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255)));

        jlblTax.setBackground(new java.awt.Color(51, 51, 51));
        jlblTax.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTax.setForeground(new java.awt.Color(255, 255, 255));
        jlblTax.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jlblTax.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255)));

        jlblAllTotal.setBackground(new java.awt.Color(51, 51, 51));
        jlblAllTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblAllTotal.setForeground(new java.awt.Color(255, 255, 255));
        jlblAllTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jlblAllTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255)));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("SubTotal:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tax:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Total:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblTax, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblSubTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblAllTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlblSubTotal)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlblTax)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblAllTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jTabbedPane2.setBackground(new java.awt.Color(51, 51, 51));
        jTabbedPane2.setForeground(new java.awt.Color(255, 0, 153));

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Lucida Sans", 1, 13)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 0, 0));
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Receipt", jPanel7);

        jPanel9.setBackground(new java.awt.Color(51, 51, 51));

        jtxtDisplay.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtDisplay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jtxtDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDisplayActionPerformed(evt);
            }
        });

        jBtn13.setFont(new java.awt.Font("Wingdings", 1, 12)); // NOI18N
        jBtn13.setText("");
        jBtn13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn13ActionPerformed(evt);
            }
        });

        jBtn7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtn7.setText("7");
        jBtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn7ActionPerformed(evt);
            }
        });

        jButton6.setText("jButton1");

        jBtn14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtn14.setText("c");
        jBtn14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn14ActionPerformed(evt);
            }
        });

        Jbtn8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Jbtn8.setText("8");
        Jbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn8ActionPerformed(evt);
            }
        });

        jBtn4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtn4.setText("4");
        jBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn4ActionPerformed(evt);
            }
        });

        jBtn5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtn5.setText("5");
        jBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn5ActionPerformed(evt);
            }
        });

        jBtn1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtn1.setText("1");
        jBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn1ActionPerformed(evt);
            }
        });

        jButton13.setText("jButton1");

        jButton14.setText("jButton1");

        jButton15.setText("jButton1");

        jBtn15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtn15.setText("+/-");
        jBtn15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn15ActionPerformed(evt);
            }
        });

        jBtn9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtn9.setText("9");
        jBtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn9ActionPerformed(evt);
            }
        });

        jBtn6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtn6.setText("6");
        jBtn6.setActionCommand("");
        jBtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn6ActionPerformed(evt);
            }
        });

        jBtn3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtn3.setText("3");
        jBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn3ActionPerformed(evt);
            }
        });

        jBtn2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtn2.setText("2");
        jBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn2ActionPerformed(evt);
            }
        });

        jBtn16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtn16.setText("+");
        jBtn16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn16ActionPerformed(evt);
            }
        });

        jBtn17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtn17.setText("-");
        jBtn17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn17ActionPerformed(evt);
            }
        });

        jBtn18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtn18.setText("*");
        jBtn18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn18ActionPerformed(evt);
            }
        });

        jBtn19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtn19.setText("/");
        jBtn19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn19ActionPerformed(evt);
            }
        });

        jBtn10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtn10.setText("0");
        jBtn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn10ActionPerformed(evt);
            }
        });

        jBtn12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtn12.setText("=");
        jBtn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn12ActionPerformed(evt);
            }
        });

        jBtn11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtn11.setText(".");
        jBtn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel9Layout.createSequentialGroup()
                                        .addComponent(jBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel9Layout.createSequentialGroup()
                                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                            .addComponent(jBtn10, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jBtn11, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel9Layout.createSequentialGroup()
                                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jBtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jBtn18, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jBtn19, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jBtn12, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jBtn7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jBtn13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(13, 13, 13)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel9Layout.createSequentialGroup()
                                        .addComponent(jBtn14, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jBtn15, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                                        .addComponent(Jbtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jBtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBtn16, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBtn17, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jtxtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                            .addGap(47, 47, 47)
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jBtn15)
                                .addComponent(jBtn16)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jBtn14)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jbtn8)
                    .addComponent(jBtn9)
                    .addComponent(jBtn7)
                    .addComponent(jBtn17))
                .addGap(6, 6, 6)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn6)
                    .addComponent(jBtn5)
                    .addComponent(jBtn4)
                    .addComponent(jBtn18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn3)
                    .addComponent(jBtn2)
                    .addComponent(jBtn1)
                    .addComponent(jBtn19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn11)
                    .addComponent(jBtn10)
                    .addComponent(jBtn12))
                .addGap(528, 528, 528)
                .addComponent(jButton13)
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton14)
                    .addComponent(jButton15))
                .addGap(456, 456, 456)
                .addComponent(jButton6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Calculator", jPanel9);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jLabel1))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(469, 469, 469)
                                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel10Layout.createSequentialGroup()
                                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(11, 11, 11)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(322, 322, 322))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(82, 82, 82))
        );

        getContentPane().add(jPanel10);
        jPanel10.setBounds(0, 0, 1510, 800);
        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCBacCheeBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBacCheeBurgerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBacCheeBurgerActionPerformed

    private void jBtn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn12ActionPerformed
       String answer;
        secondnum = Double.parseDouble( jtxtDisplay.getText());
      
        if (operations == "+")
        {
            result = firstnum + secondnum;
            answer = String.format("%.2f", result);
            jtxtDisplay.setText(answer);
            
        }
        
        else if (operations == "-")
        {
            result = firstnum - secondnum;
            answer = String.format("%.2f", result);
            jtxtDisplay.setText(answer);
            
        }
        
        else  if (operations == "*")
        {
            result = firstnum * secondnum;
            answer = String.format("%.2f", result);
            jtxtDisplay.setText(answer);
            
        }
        
      else   if (operations == "/")
        {
            result = firstnum / secondnum;
            answer = String.format("%.2f", result);
            jtxtDisplay.setText(answer);
            
        }
        
        else  if (operations == "%")
        {
            result = firstnum % secondnum;
            answer = String.format("%.2f", result);
            jtxtDisplay.setText(answer);
            
        }
        
    }//GEN-LAST:event_jBtn12ActionPerformed

    private void jBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn2ActionPerformed
          String Enternumber = jtxtDisplay.getText() + jBtn2.getText();
     jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBtn2ActionPerformed

    private void jBtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn6ActionPerformed
       String Enternumber = jtxtDisplay.getText() + jBtn6.getText();
     jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBtn6ActionPerformed

    private void jBtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn9ActionPerformed
        String Enternumber = jtxtDisplay.getText() + jBtn9.getText();
     jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBtn9ActionPerformed

    private void jBtn15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn15ActionPerformed
       double ops = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
       ops =ops * (-1);
       jtxtDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jBtn15ActionPerformed

    private void jBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn1ActionPerformed
        String Enternumber = jtxtDisplay.getText() + jBtn1.getText();
     jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBtn1ActionPerformed

    private void jBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn5ActionPerformed
          String Enternumber = jtxtDisplay.getText() + jBtn5.getText();
     jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBtn5ActionPerformed

    private void jBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn4ActionPerformed
     String Enternumber = jtxtDisplay.getText() + jBtn4.getText();
     jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBtn4ActionPerformed

    private void Jbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn8ActionPerformed
       String Enternumber = jtxtDisplay.getText() + Jbtn8.getText();
     jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_Jbtn8ActionPerformed

    private void jBtn14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn14ActionPerformed
      jtxtDisplay.setText(null);  
    }//GEN-LAST:event_jBtn14ActionPerformed

    private void jBtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn7ActionPerformed
     String Enternumber = jtxtDisplay.getText() + jBtn7.getText();
     jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBtn7ActionPerformed

    private void jtxtDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDisplayActionPerformed

    private void jBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn3ActionPerformed
         String Enternumber = jtxtDisplay.getText() + jBtn3.getText();
     jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBtn3ActionPerformed

    private void jBtn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn10ActionPerformed
         String Enternumber = jtxtDisplay.getText() + jBtn10.getText();
     jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBtn10ActionPerformed

    private void jBtn13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn13ActionPerformed
       String backspace=null;
      
       if(jtxtDisplay.getText(). length() > 0){
           StringBuilder strB = new StringBuilder(jtxtDisplay.getText());
           strB.deleteCharAt(jtxtDisplay.getText(). length() - 1);
           backspace = strB.toString();
           jtxtDisplay.setText(backspace);
       }
   
    }//GEN-LAST:event_jBtn13ActionPerformed

    private void jBtn16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn16ActionPerformed
      
                                         
        firstnum = Double.parseDouble(jtxtDisplay.getText());
    
   
 
     jtxtDisplay.setText("");
     operations="+";
    }//GEN-LAST:event_jBtn16ActionPerformed

    private void jBtn17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn17ActionPerformed
        firstnum = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText("");
        operations="-";
    }//GEN-LAST:event_jBtn17ActionPerformed

    private void jBtn18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn18ActionPerformed
        firstnum = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText("");
        operations="*";
    }//GEN-LAST:event_jBtn18ActionPerformed

    private void jBtn19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn19ActionPerformed
         firstnum = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText("");
        operations="/";
    }//GEN-LAST:event_jBtn19ActionPerformed

    private void jBtn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn11ActionPerformed
             String Enternumber = jtxtDisplay.getText() + jBtn11.getText();
     jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBtn11ActionPerformed

    private void jBtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCloseActionPerformed
       jtxConvertor.setText(null);
       jlblConvertor.setText(null);
       jcmbCurrency.setSelectedIndex(0);
    }//GEN-LAST:event_jBtnCloseActionPerformed

    private void jBtnConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConvertActionPerformed
        double Bangladeshi_Taka = Double.parseDouble(jtxConvertor.getText());
        
        if(jcmbCurrency.getSelectedItem().equals("USA"))
        {
        String cConvert1 = String.format("$ %.2f", Bangladeshi_Taka * US_Dollar);
        jlblConvertor.setText(cConvert1 );
       
       }
        if(jcmbCurrency.getSelectedItem().equals("Canada"))
        {
        String cConvert1 = String.format("C$ %.2f", Bangladeshi_Taka * Cnadian_Dollar);
        jlblConvertor.setText(cConvert1 );
       
       }
        if(jcmbCurrency.getSelectedItem().equals("India"))
        {
        String cConvert1 = String.format("₹ %.2f", Bangladeshi_Taka * Indian_Rupee);
        jlblConvertor.setText(cConvert1 );
       
       }
        if(jcmbCurrency.getSelectedItem().equals("Japan"))
        {
        String cConvert1 = String.format("¥ %.2f", Bangladeshi_Taka * Japanese_Yen);
        jlblConvertor.setText(cConvert1 );
       
       }
        if(jcmbCurrency.getSelectedItem().equals("Sri Lanka"))
        {
        String cConvert1 = String.format("₨ %.2f", Bangladeshi_Taka * SriLanka_Rupee);
        jlblConvertor.setText(cConvert1 );
       
       }
        if(jcmbCurrency.getSelectedItem().equals("China"))
        {
        String cConvert1 = String.format("¥ %.2f", Bangladeshi_Taka * Chinese_Yuan_Renminbi);
        jlblConvertor.setText(cConvert1 );
       
       }
        
        
    }//GEN-LAST:event_jBtnConvertActionPerformed

    private void jBtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExitActionPerformed
           System.exit(0);
    }//GEN-LAST:event_jBtnExitActionPerformed

    private void jcmbDrinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbDrinkActionPerformed
           double Coffe= 30;
           double Cold_Coffe= 40;
           double Ice_Tea= 40;
           double Apple_juece= 80;
           double Lassi= 50;
        
        if(jcmbDrink.getSelectedItem().equals("Coffe"))
        {
        String cCoffe = String.format(" %.2f",Coffe);
        jlblCostodDrinks.setText(cCoffe );
       
       }
         if(jcmbDrink.getSelectedItem().equals("Cold Coffe"))
        {
        String cCold_Coffe = String.format(" %.2f",Cold_Coffe);
        jlblCostodDrinks.setText(cCold_Coffe );
       
       }
          if(jcmbDrink.getSelectedItem().equals("Ice Tea"))
        {
        String cIce_Tea = String.format(" %.2f",Ice_Tea);
        jlblCostodDrinks.setText(cIce_Tea );
       
       }
           if(jcmbDrink.getSelectedItem().equals("Apple juece"))
        {
        String cApple_juece = String.format(" %.2f",Apple_juece);
        jlblCostodDrinks.setText(cApple_juece );
       
       }
            if(jcmbDrink.getSelectedItem().equals("Lassi"))
        {
        String cLassi = String.format(" %.2f",Lassi);
        jlblCostodDrinks.setText(cLassi );
       
       }
              if(jcmbDrink.getSelectedItem().equals("Select a Drink"))
        {
        
        jlblCostodDrinks.setText(null );
       
       } 
            
            
            
    }//GEN-LAST:event_jcmbDrinkActionPerformed

    private void jCDeliveryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCDeliveryMouseClicked
       double  iDelivery = 100;
       if (jCDelivery.isSelected())
       {
          String pDelivary = String.format(" %.2f", iDelivery);
          jlblCostofDelivary.setText(pDelivary);
           
         }
        else
       {
            jlblCostofDelivary.setText(null);
       }
    }//GEN-LAST:event_jCDeliveryMouseClicked

    private void jCDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCDeliveryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCDeliveryActionPerformed

    private void jBtnReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnReceiptActionPerformed
        
          if(jCChickBurger.isSelected()){
          double Quyt1 = Double.parseDouble(jtxChickBurger.getText());
        // double Quyt2 = Double.parseDouble(jtxChickBurgerMeal.getText());
        // double Quyt3 = Double.parseDouble(jtxBacCheeBurger.getText());
        double Quyt4 = Double.parseDouble(jlblSubTotal.getText());
         double Quyt5 = Double.parseDouble(jlblTax.getText());
          double Quyt6 = Double.parseDouble(jlblAllTotal.getText());
    double Quyt7 = jlblCostodDrinks.getText().length() > 0 ? Double.parseDouble(jlblCostodDrinks.getText()) : 0;
         jTextArea1.append("\tReceipt\n\n" + "Chicken Burger: Tk 100\t" + Quyt1 + 
               //  "\nChicken Burger Meal:\t" + Quyt2 +
               //  "\n Beacon and Chees Burger:\t"+ Quyt3 +
                 "\nCost of drinks: Tk " + Quyt7 +
                 "\n\nSub Total: Tk\t" + Quyt4 +
                 
                 "\nTax: Tk\t" + Quyt5 + "\nTotal: Tk\t" + Quyt6 +
                 
                 
                 "\n\nThanks for Comming" );
                 
          } 
                  if(jCChickBurgerMeal.isSelected()){
        //  double Quyt1 = Double.parseDouble(jtxChickBurger.getText());
         double Quyt2 = Double.parseDouble(jtxChickBurgerMeal.getText());
        // double Quyt3 = Double.parseDouble(jtxBacCheeBurger.getText());
        double Quyt4 = Double.parseDouble(jlblSubTotal.getText());
         double Quyt5 = Double.parseDouble(jlblTax.getText());
          double Quyt6 = Double.parseDouble(jlblAllTotal.getText());
       double Quyt7 = jlblCostodDrinks.getText().length() > 0 ? Double.parseDouble(jlblCostodDrinks.getText()) : 0;
         
         jTextArea1.append("\tReceipt\n\n" +// "Chicken Burger:\t" + Quyt1 + 
                "\nChicken Burger Meal: Tk 200\t" + Quyt2 +
                 "\nCost of drinks: Tk " + Quyt7 +
               //  "\n Beacon and Chees Burger:\t"+ Quyt3 +
                 "\n\nSub Total: Tk\t" + Quyt4 +
                 
                 "\nTax: Tk\t" + Quyt5 + "\nTotal: Tk\t" + Quyt6 +
                 
                 
                 "\n\nThanks for Comming" );
                 
          } 
                 if(jCBacCheeBurger.isSelected()){
        //  double Quyt1 = Double.parseDouble(jtxChickBurger.getText());
        // double Quyt2 = Double.parseDouble(jtxChickBurgerMeal.getText());
         double Quyt3 = Double.parseDouble(jtxBacCheeBurger.getText());
        double Quyt4 = Double.parseDouble(jlblSubTotal.getText());
         double Quyt5 = Double.parseDouble(jlblTax.getText());
          double Quyt6 = Double.parseDouble(jlblAllTotal.getText());
          double Quyt7 = jlblCostodDrinks.getText().length() > 0 ? Double.parseDouble(jlblCostodDrinks.getText()) : 0;
          
         
         jTextArea1.append("\tReceipt\n\n" +// "Chicken Burger:\t" + Quyt1 + 
               //  "\nChicken Burger Meal:\t" + Quyt2 +
                 "\n Beacon and Chees Burger: Tk 250\t"+ Quyt3 +
                 "\nCost of drinks: Tk " + Quyt7 +
                 "\n\nSub Total: Tk\t" + Quyt4 +
                 
                 "\nTax: Tk\t" + Quyt5 + "\nTotal: Tk\t" + Quyt6 +
                 
                 
                 "\n\nThanks for Comming" );
                 
          } 
                
                          if(jtxChickBurgerMeal.getVerifyInputWhenFocusTarget()){
           if (jtxBacCheeBurger.getVerifyInputWhenFocusTarget()) {
               //  double Quyt1 = Double.parseDouble(jtxChickBurger.getText());
               double Quyt2 = Double.parseDouble(jtxChickBurgerMeal.getText());
               double Quyt3 = Double.parseDouble(jtxBacCheeBurger.getText());
               double Quyt4 = Double.parseDouble(jlblSubTotal.getText());
               double Quyt5 = Double.parseDouble(jlblTax.getText());
               double Quyt6 = Double.parseDouble(jlblAllTotal.getText());
          double Quyt7 = jlblCostodDrinks.getText().length() > 0 ? Double.parseDouble(jlblCostodDrinks.getText()) : 0;
               
               jTextArea1.append("\tReceipt\n\n" +   "\nChicken Burger Meal: Tk 200\t" + Quyt2 + "\n Beacon and Chees Burger: Tk 205\t"+ Quyt3 +   "\nCost of drinks: Tk " + Quyt7 + "\n\nSub Total: Tk\t" + Quyt4 +  "\nTax: Tk\t" + Quyt5 + "\nTotal: Tk\t" + Quyt6 +
                       
                       
                       
                       
                       
                       
                       
                       "\n\nThanks for Comming" );
           }
                 
          } 
                          
                        
                          if(jtxChickBurgerMeal.getVerifyInputWhenFocusTarget()){
           if (jtxChickBurger.getVerifyInputWhenFocusTarget()) {
                double Quyt1 = Double.parseDouble(jtxChickBurger.getText());
               double Quyt2 = Double.parseDouble(jtxChickBurgerMeal.getText());
              // double Quyt3 = Double.parseDouble(jtxBacCheeBurger.getText());
               double Quyt4 = Double.parseDouble(jlblSubTotal.getText());
               double Quyt5 = Double.parseDouble(jlblTax.getText());
               double Quyt6 = Double.parseDouble(jlblAllTotal.getText());
              double Quyt7 = jlblCostodDrinks.getText().length() > 0 ? Double.parseDouble(jlblCostodDrinks.getText()) : 0;
               
               jTextArea1.append("\tReceipt\n\n" + "Chicken Burger: Tk 100\t" + Quyt1 +  "\nChicken Burger Meal: Tk 200\t" + Quyt2 +   "\nCost of drinks: Tk " + Quyt7 +   "\n\nSub Total: Tk\t" + Quyt4 +  "\nTax: Tk\t" + Quyt5 + "\nTotal: Tk\t" + Quyt6 +
                       
                       
                       
                       
                       
                       
                       
                       "\n\nThanks for Comming" );
           }
                 
          } 
                                   
                          if(jtxChickBurger.getVerifyInputWhenFocusTarget()){
           if (jtxBacCheeBurger.getVerifyInputWhenFocusTarget()) {
                double Quyt1 = Double.parseDouble(jtxChickBurger.getText());
             //  double Quyt2 = Double.parseDouble(jtxChickBurgerMeal.getText());
               double Quyt3 = Double.parseDouble(jtxBacCheeBurger.getText());
               double Quyt4 = Double.parseDouble(jlblSubTotal.getText());
               double Quyt5 = Double.parseDouble(jlblTax.getText());
               double Quyt6 = Double.parseDouble(jlblAllTotal.getText());
              double Quyt7 = jlblCostodDrinks.getText().length() > 0 ? Double.parseDouble(jlblCostodDrinks.getText()) : 0;
               
               jTextArea1.append("\tReceipt\n\n" + "Chicken Burger: Tk 100\t" + Quyt1 +   "\n Beacon and Chees Burger: Tk 250\t"+ Quyt3 +   "\nCost of drinks: Tk " + Quyt7 +  "\n\nSub Total: Tk\t" + Quyt4 +  "\nTax: Tk\t" + Quyt5 + "\nTotal: Tk\t" + Quyt6 +
                       
                       
                       
                       
                       
                       
                       
                       "\n\nThanks for Comming" );
           }
                 
          } 
                          
                          
                if(jtxChickBurgerMeal.getVerifyInputWhenFocusTarget()){
                
                 
                          if(jtxChickBurgerMeal.getVerifyInputWhenFocusTarget()){
           if (jtxBacCheeBurger.getVerifyInputWhenFocusTarget()) {
                double Quyt1 = Double.parseDouble(jtxChickBurger.getText());
               double Quyt2 = Double.parseDouble(jtxChickBurgerMeal.getText());
               double Quyt3 = Double.parseDouble(jtxBacCheeBurger.getText());
               double Quyt4 = Double.parseDouble(jlblSubTotal.getText());
               double Quyt5 = Double.parseDouble(jlblTax.getText());
               double Quyt6 = Double.parseDouble(jlblAllTotal.getText());
               double Quyt7 = jlblCostodDrinks.getText().length() > 0 ? Double.parseDouble(jlblCostodDrinks.getText()) : 0;
               
               jTextArea1.append("\tReceipt\n\n" + "Chicken Burger: Tk 100\t" + Quyt1 +   "\nChicken Burger Meal: Tk 200\t" + Quyt2 + "\n Beacon and Chees Burger: Tk 250\t"+ Quyt3 +  "\nCost of drinks: Tk " + Quyt7 +  "\n\nSub Total: Tk\t" + Quyt4 +  "\nTax: Tk\t" + Quyt5 + "\nTotal: Tk\t" + Quyt6 +
                       
                       
                       
                       
                       
                       
                       
                       "\n\nThanks for Comming" );
           }
                 
          } 
                }     
                
    }//GEN-LAST:event_jBtnReceiptActionPerformed

    private void jBtnReceiptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnReceiptMouseClicked
       
    }//GEN-LAST:event_jBtnReceiptMouseClicked

    private void jCChickBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCChickBurgerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCChickBurgerActionPerformed

    private void jCChickBurgerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCChickBurgerMouseClicked
      double cMeal = Double.parseDouble(jlblCostofMeal.getText());
      double chicBurger = Double.parseDouble(jtxChickBurger.getText());
      double ichicBurger = 100;
      
      if(jCChickBurger.isSelected())
      {
          i[0] = (chicBurger * ichicBurger) + cMeal;
          String pMeal = String.format(" %.2f", i[0]);
          jlblCostofMeal.setText(pMeal);
      }
      
    }//GEN-LAST:event_jCChickBurgerMouseClicked

    private void jCChickBurgerMealMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCChickBurgerMealMouseClicked
       double cMeal = Double.parseDouble(jlblCostofMeal.getText());
      double chicBurgerMEal = Double.parseDouble(jtxChickBurgerMeal.getText());
      double ichicBurgerMeal = 200;
      
      if(jCChickBurgerMeal.isSelected())
      {
          i[1] = ((chicBurgerMEal * ichicBurgerMeal) + cMeal);
          String pMeal = String.format(" %.2f", i[1]);
          jlblCostofMeal.setText(pMeal);
      }
      
    }//GEN-LAST:event_jCChickBurgerMealMouseClicked

    private void jCBacCheeBurgerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCBacCheeBurgerMouseClicked
         double cMeal = Double.parseDouble(jlblCostofMeal.getText());
      double BCBurger = Double.parseDouble(jtxBacCheeBurger.getText());
      double iBCBurger = 250;
      
      if(jCBacCheeBurger.isSelected())
      {
          i[2] = ((BCBurger * iBCBurger) + cMeal);
          String pMeal = String.format(" %.2f", i[2]);
          jlblCostofMeal.setText(pMeal);
      }
    }//GEN-LAST:event_jCBacCheeBurgerMouseClicked

    private void jCChickBurgerMealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCChickBurgerMealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCChickBurgerMealActionPerformed

    private void jCTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTaxActionPerformed
       
        
          if  (jlblCostofMeal.getVerifyInputWhenFocusTarget()){
                double cTotal2 = Double.parseDouble(jlblCostofMeal.getText());
                
            double pTotal1 = (cTotal2/100);
                    String iTotal4 = String.format(" %.2f", pTotal1);
                      jlblTax.setText(iTotal4);
                      
    }                                     

          
       
         if (jlblCostofMeal.getVerifyInputWhenFocusTarget() && jlblCostodDrinks.getVerifyInputWhenFocusTarget() ){
            double cTotal1 = Double.parseDouble(jlblCostodDrinks.getText());
             double cTotal2 = Double.parseDouble(jlblCostofMeal.getText());
             double aTotal2 = (cTotal1 + cTotal2 )/100;
                 String iTotal2 = String.format(" %.2f", aTotal2);
                      jlblTax.setText(iTotal2);
            
        }
        
        
              if  (jlblCostofDelivary.getVerifyInputWhenFocusTarget() && jlblCostodDrinks.getVerifyInputWhenFocusTarget() && jlblCostofMeal.getVerifyInputWhenFocusTarget() ){
             double cTotal3 = Double.parseDouble(jlblCostofDelivary.getText());
            double cTotal1 = Double.parseDouble(jlblCostodDrinks.getText());
             double cTotal2 = Double.parseDouble(jlblCostofMeal.getText());
             
             double aTotal3 = (cTotal1 + cTotal2 + cTotal3 )/100;
                 String iTotal3 = String.format(" %.2f", aTotal3);
                      jlblTax.setText(iTotal3);
             }
              
         if (jlblCostodDrinks.getVerifyInputWhenFocusTarget()){
                double cTotal1 = Double.parseDouble(jlblCostodDrinks.getText());
                
            double aTotal1 = cTotal1/100;
                  String iTotal = String.format(" %.2f", aTotal1);
                      jlblTax.setText(iTotal);
        }
         
         
        
          
                
                      
    }//GEN-LAST:event_jCTaxActionPerformed

       
         
       
                 
        
        
    private void jCTaxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCTaxMouseClicked

        
       
       if (jlblCostofMeal.getVerifyInputWhenFocusTarget() &&jlblCostofDelivary.getVerifyInputWhenFocusTarget() ){
            double cTotal3 = Double.parseDouble(jlblCostofDelivary.getText());
             double cTotal2 = Double.parseDouble(jlblCostofMeal.getText());
             double aTotal4 = (cTotal3 + cTotal2 )/100;
                 String iTotal4 = String.format(" %.2f", aTotal4);
                      jlblTax.setText(iTotal4);
            
        }
          
              if (jlblCostodDrinks.getVerifyInputWhenFocusTarget() &&jlblCostofDelivary.getVerifyInputWhenFocusTarget() ){
            double cTotal3 = Double.parseDouble(jlblCostofDelivary.getText());
            double cTotal1 = Double.parseDouble(jlblCostodDrinks.getText());
             double aTotal4 = (cTotal3 + cTotal1 )/100;
                 String iTotal4 = String.format(" %.2f", aTotal4);
                      jlblTax.setText(iTotal4);
            
        }
              
              if  (jlblCostofDelivary.getVerifyInputWhenFocusTarget() && jlblCostodDrinks.getVerifyInputWhenFocusTarget() && jlblCostofMeal.getVerifyInputWhenFocusTarget() ){
             double cTotal3 = Double.parseDouble(jlblCostofDelivary.getText());
            double cTotal1 = Double.parseDouble(jlblCostodDrinks.getText());
             double cTotal2 = Double.parseDouble(jlblCostofMeal.getText());
             
             double aTotal3 = (cTotal1 + cTotal2 + cTotal3 )/100;
                 String iTotal3 = String.format(" %.2f", aTotal3);
                      jlblTax.setText(iTotal3);
             }
          
       
       
                
          
                  
                     
        
       // double cTotal1 = Double.parseDouble(jlblCostodDrinks.getText());
       // double cTotal2 = Double.parseDouble(jlblCostofMeal.getText());
       // double cTotal3 = Double.parseDouble(jlblCostofDelivary.getText());
        
       // double allTotal =( cTotal1 + cTotal2 + cTotal3 )/100 ;
      //  String iTotal = String.format(" %.2f", allTotal);
        
        // jlblTax.setText(iTotal);
         
         
        
       
       
    }//GEN-LAST:event_jCTaxMouseClicked

    private void jBtnTotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTotalMouseClicked
       
        
         double cTotal1 = jlblCostodDrinks.getText().length() > 0 ? Double.parseDouble(jlblCostodDrinks.getText()) : 0;
         double cTotal2 = jlblCostofMeal.getText().length() > 0 ? Double.parseDouble(jlblCostofMeal.getText()) : 0;
       // double cTotal2 = Double.parseDouble(jlblCostofMeal.getText());
       // double cTotal3 = Double.parseDouble(jlblCostofDelivary.getText());
        double cTotal3 = jlblCostofDelivary.getText().length() > 0 ? Double.parseDouble(jlblCostofDelivary.getText()) : 0;
        double cTotal4 = Double.parseDouble(jlblTax.getText());
      // double cTotal3 = jlblCostofDelivary.getText().length() > 0 ? Double.parseDouble(jlblCostofDelivary.getText()) : 0;
        
     
      double subTota =( cTotal1 + cTotal2 + cTotal3  ) ;
     String isubTota = String.format(" %.2f", subTota);
     jlblSubTotal.setText(isubTota);
       
       
       
      
        
           double allTotal =( cTotal1 + cTotal2 + cTotal3 + cTotal4 ) ;
             String iTotal = String.format(" %.2f", allTotal);
            jlblAllTotal.setText(iTotal);
            
          
         // String itaxTotal = String.format("৳, %.2f", cTotal4);
         // jlblTax.setText(itaxTotal);
          
          
          
        
            
        
       
       
       
       
       
     
        
          
              
        
        
        
        
       
        
    }//GEN-LAST:event_jBtnTotalMouseClicked

    private void jlblCostofDelivaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlblCostofDelivaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlblCostofDelivaryActionPerformed

    private void jBtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnResetActionPerformed
        jlblCostofDelivary.setText(null);
        jlblCostofMeal.setText("0");
        jlblCostodDrinks.setText(null);
        jlblConvertor.setText(null);
        jlblSubTotal.setText(null);
        jlblTax.setText(null);
        jlblAllTotal.setText(null);
        jtxChickBurger.setText(null);
        jtxChickBurgerMeal.setText(null);
        jtxBacCheeBurger.setText(null);
        jTextArea1.setText(null);
        jCChickBurger.setSelected(false);
        jCChickBurgerMeal.setSelected(false);
        jCBacCheeBurger.setSelected(false);
        jCDelivery.setSelected(false);
        jCTax.setSelected(false);
        jcmbDrink.setSelectedIndex(0);
         
         
    }//GEN-LAST:event_jBtnResetActionPerformed

    private void jtxChickBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxChickBurgerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxChickBurgerActionPerformed

    private void jlblCostodDrinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlblCostodDrinksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlblCostodDrinksActionPerformed

    private void jBtnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTotalActionPerformed
       
        
          
              
    }//GEN-LAST:event_jBtnTotalActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        RegEmp r = new RegEmp();
        r.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Restaurants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Restaurants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Restaurants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Restaurants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Restaurants().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jbtn8;
    private javax.swing.JButton jBtn1;
    private javax.swing.JButton jBtn10;
    private javax.swing.JButton jBtn11;
    private javax.swing.JButton jBtn12;
    private javax.swing.JButton jBtn13;
    private javax.swing.JButton jBtn14;
    private javax.swing.JButton jBtn15;
    private javax.swing.JButton jBtn16;
    private javax.swing.JButton jBtn17;
    private javax.swing.JButton jBtn18;
    private javax.swing.JButton jBtn19;
    private javax.swing.JButton jBtn2;
    private javax.swing.JButton jBtn3;
    private javax.swing.JButton jBtn4;
    private javax.swing.JButton jBtn5;
    private javax.swing.JButton jBtn6;
    private javax.swing.JButton jBtn7;
    private javax.swing.JButton jBtn9;
    private javax.swing.JButton jBtnClose;
    private javax.swing.JButton jBtnConvert;
    private javax.swing.JButton jBtnExit;
    private javax.swing.JButton jBtnReceipt;
    private javax.swing.JButton jBtnReset;
    private javax.swing.JButton jBtnTotal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton6;
    private javax.swing.JCheckBox jCBacCheeBurger;
    private javax.swing.JCheckBox jCChickBurger;
    private javax.swing.JCheckBox jCChickBurgerMeal;
    private javax.swing.JCheckBox jCDelivery;
    private javax.swing.JCheckBox jCTax;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox<String> jcmbCurrency;
    private javax.swing.JComboBox<String> jcmbDrink;
    private javax.swing.JTextField jlblAllTotal;
    private javax.swing.JLabel jlblConvertor;
    private javax.swing.JTextField jlblCostodDrinks;
    private javax.swing.JTextField jlblCostofDelivary;
    private javax.swing.JTextField jlblCostofMeal;
    private javax.swing.JTextField jlblSubTotal;
    private javax.swing.JTextField jlblTax;
    private javax.swing.JTextField jtxBacCheeBurger;
    private javax.swing.JTextField jtxChickBurger;
    private javax.swing.JTextField jtxChickBurgerMeal;
    private javax.swing.JTextField jtxConvertor;
    private javax.swing.JTextField jtxtDisplay;
    // End of variables declaration//GEN-END:variables

    private void setBackgroung(Color color) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
